apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 15s
      queryTimeout: 30s

  - name: TimescaleDB
    type: postgres
    access: proxy
    url: timescaledb:5432
    database: field_hospital
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: true
      maxOpenConns: 10
      maxIdleConns: 2
      connMaxLifetime: 14400
    editable: true
